### ISSUE TITLE
Metadata of surface missing in surface download

### ISSUE THREAD

**Issue by mcrot** [ContactEngineering/TopoBank#552]
I've just downloaded a surface and the file `meta.yml` has the meta information about all topographies,
but not about the surface itself.  Thinks like description, name and tags are missing. The file is a list of topographies on the top level.

This would be needed to reimport the surface into the application, see #239 .

**Comment by mcrot** [comment]
@pastewka , what do you think about a more complex structure here in `meta.yml`?
For example
```
name: UNCD
description: ..........
category: exp
tags: diamond, exp1
creator:
topographies:     # old contents here
  - name: topo1
    ...
  - name: topo2
    ...
```
